language: node_js
node_js:
- '4.1'
- stable
notifications:
  slack:
    secure: k5K1kvueXpFqK4DIVNWUhYWfJI4dQF24L7+txYrhAcjo02Y7HOhFknphZ5nz/WZEvAcLxwzCq9gg5RCXMQXL0Jsby9GEpqKMRP1yApijfWHzKeTM/eexAdHyCf7Aj6i1aual+AoYfn1LAMPto+klFw/q6YwzAZp0UEu414DAhGY4oy1KBRzDlSgeP/WBCsWHTqI8lWYYQqT7iR8GBgyTB/M7nx8IIeoDUSHUGXPZQv2klXpDkH9lEzTo8Rx1GUAeRr63WIfCb+HuVEFztqDi1TUmpoAuZMO6Q1do69G+ZkJzjgTWpichWd4t7E8UGcurzWWFiSCtFrRqPpQJrrd6ykEtExe3jbfqA0PAbgY7T54wj3U/cbA3w9DBWoBpioIbYu0lFk7pPztjwCGt7IxxLhURPP0qFynzhBEOvn0xJZPM+dGjrOwV7FEBanLW4XUEYOHV4dN3iQmMII7V46MWstP5G+39XxIL+Ls+/jnKsBcLvegxClvHgY+SR1sMDS0FjnsK+eB2W/pthnBJ3U7X/hENqcAxqUfm2yM+RQOCmy4s++Ywk+U7amdaxuAbyWMAhOx1ZX+M5Bzg8dwLI4XjAdWHh9iduqHnOCpfa2swtVYIDp9r2BFaaKDSjuswEQBq4a9bebnApw7akVl5ycMIPlGgOYNW2hSUJzt6/VqwZ0U=
deploy:
  provider: npm
  email: no-reply@peopleplan.com.au
  on:
    tags: true
  api_key:
    secure: YHiLzflWPLOxAKlIqHSfU+V8s2QOQG2crkm6G0pOiM3wb1IcCwoiyqX04IOQtgnrujTrN9jCY43uAhxd7NiYkRle4ayTHgOI9gmhzXbLNYOuyb2f6ituutbFJSncukwGZN3Mm2F/rWygTcExkFevCZ3Ce3XTK23cm+KXTBm/j4TWHCODZmgtcBAga1lp7ZUs2xv/vTxn2zvxRe1WMHiAGlFAoNN94r/S1xTPWv4GKgVHimGaxL/BsRMA1hRmsz+6k2FYLHKP8qeur3TtWJLUQ4tZWNLxCZrE6PPzWhtaHprxH9qQFV5+y2xOlR+IrnWiOHw1aigooCcGi+h4o6BcEG1LINB0iyOvuMPO4JL5dR+/0uc4KvsfrLhkggGOV+QLw4OeVTa4NLiYIHSizg+az6qag0tQoEZrn8KcXKhJVMg0VELC28CBsUPN0B9EInACPFlSoWO3kY/Ti20i/q2/3IUdOhDlXbKeY86IeL+lZySCgcBFLFjkC3LeM+fR5meWWjy7otbp9LbHXYhz+tuf2FXeik+cQHcNtoMOuLps334G85CEtcJ4xXoOdDzlJDSqDeqLMrNiZUCCbiHj94iV7f8HQThQ+uxHN2GiHHtXW4lLsDuRWnrxPM9BLetzPpJBCums1Jrb75187nsfW5afw1Qzjm9puNYB6mDuDERyG6Q=
